---
title: "Macleish Project"
author: "Ben Raivel"
date: "4/6/2019"
output:
  html_document:
    code_folding: hide 
---

```{r, message = FALSE}
library(tidyverse)
library(sf)
library(macleish)
library(utils)

mass_gis1 <- function (layer = "contours5k/hp68") 
{
  dir <- tempdir()
  url <- "http://download.massgis.digital.mass.gov/shapefiles/contours5k/hp68.zip"
  lcl_zip <- file.path(dir, basename(url))
  utils::download.file(url, destfile = lcl_zip)
  lcl_shp <- file.path(dir, layer)
  utils::unzip(lcl_zip, exdir = lcl_shp)
  sf::st_read(lcl_shp) %>% sf::st_transform(4326)
}
mass_gis2 <- function (layer = "contours5k/hp337") 
{
  dir <- tempdir()
  url <- "http://download.massgis.digital.mass.gov/shapefiles/contours5k/hp337.zip"
  lcl_zip <- file.path(dir, basename(url))
  utils::download.file(url, destfile = lcl_zip)
  lcl_shp <- file.path(dir, layer)
  utils::unzip(lcl_zip, exdir = lcl_shp)
  sf::st_read(lcl_shp) %>% sf::st_transform(4326)
}

macleish_intersect <- function (x) 
{
  sf::st_intersection(macleish::macleish_layers[["boundary"]], 
    x)
}

elevation1 <- mass_gis1()
elevation2 <- mass_gis2()

macleish_elevation1 <- macleish_intersect(elevation1)
macleish_elevation2 <- macleish_intersect(elevation2)
```

```{r, message = FALSE}
library(leaflet)
#library(lwgeom)
#install using devtools::install_github("jmt2080ad/polylineSplitter")


trails <- macleish_layers %>%
  pluck("trails")


#splitfun <- function(splitPoints)

 
macleish_elevation <- rbind(macleish_elevation1, macleish_elevation2)
 
#trails_sp <- as(macleish_elevation, Class = "Spatial")
#daSplitShit <- splitLines(trails_sp, 100)
#split_sf <- st_as_sf(daSplitShit)
#split_sf_lines <- st_set_crs(st_cast(split_sf, "LINESTRING"), 4326)
 

trail_contour_intersect <- st_intersection(trails, macleish_elevation)

contour_multi <- st_cast(trail_contour_intersect, "MULTIPOINT")

contour_point <- st_cast(contour_multi, "POINT")

data <- contour_point %>%
  group_by(name) %>%
  summarise(N = n())

pal <- colorNumeric(palette = "Blues", domain = macleish_elevation$ELEV_M)

#joined_intersections <- st_join(macleish_elevation, trails, join = st_intersects)

#joined_intersection_points <- st_cast(joined_intersections, "POINT")

leaflet() %>%
  addTiles() %>%
  addPolylines(data = trails, color = "red") %>%
  addPolylines(data = macleish_elevation, color = ~pal(ELEV_M)) %>%
  addMarkers(data = contour_point) 




```

```{r}
data2 <- st_cast(data, "LINESTRING")

leaflet() %>%
  addTiles() %>%
  addPolylines(data = data2)
```

```{r}

trails2 <- data %>%
  select(name, N) %>%
  st_set_geometry(NULL) %>%
  right_join(trails) %>%
  mutate(length = st_length(trails)) %>%
  group_by(name) %>%
  summarize(n = max(N), length = sum(length)) %>%
  mutate(rating = sqrt(n*unclass(length))) %>%
  mutate(class = ifelse(rating > 2/3 * max(rating), "Most Difficult", ifelse(rating > 1/3 * max(rating), "Moderate", "Easiest"))) %>%
  sort(desc(rating))

#trails3 <- left_join(trails, trails2) %>%
  #mutate(length = st_length(trails))
  
palette1 <- colorNumeric(
  palette = "Blues",
  domain = data$difficulty)

snowtrail <- filter(trails, name == "Snowmobile Trail")

leaflet() %>%
  addTiles() %>%
  addPolylines(data = trails3, color = ~palette1(difficulty))

ggplot(snowtrail) +
  geom_sf()
```




